title: "Gazi A. Raihan"
author: "Gazi Raihan"
description: "University of New Orleans"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false       # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}

  - {file: "README.md", title: "About me"}
  - {file: "/research.md", title: "Research"}
  - {title: "Publications", file: "publication.md"}
  - {title: "Teaching & Outreach", file:"/teaching.md"}
  - {title: "CV", file: "/raihan.pdf"}
  - {title: "Contact", file:"contact.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "graihan@uno.edu"}
  - {title: Github, icon: github, url: "https://github.com/raihan57"}
  - {title: Twitter, icon: twitter, url: "www.twitter.com/raihan57"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
